Migrate ACS from policyengine-us
PolicyEngine/policyengine-us-data pull request #35
Opened 2024-09-09 21:04 UTC by PavelMakarchuk

Fixes #31

2024-09-09 21:08 UTC, MaxGhenis commented
Have you tried running it?

2024-09-13 11:13 UTC, nikhilwoodruff commented on acs.py
Can you remove this from the repo and add a test generating the dataset?

2024-09-13 11:13 UTC, nikhilwoodruff commented on policyengine_us_data/datasets/acs/acs.py
> +class ACS_2022(ACS):
LGTM, and just 2022 is fine!

2024-09-14 17:20 UTC, PavelMakarchuk commented on acs.py
I have create a test to see if the ACS is generated but nothing else - no loading or checking tables etc

2024-09-14 19:21 UTC, MaxGhenis requested changes
Could you add `acs/README.md` linking to the codebook?

Also if easy, could you add rent and property tax as variables?

2024-09-15 12:40 UTC, PavelMakarchuk commented
> Could you add `acs/README.md` linking to the codebook?
> 
> Also if easy, could you add rent and property tax as variables?

Added a readme with documentation

We already include 
GRNTP -> Gross Rent
RNTP -> Monthly rent

I don't see variables for property taxes in the [dictionary](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2022.pdf)

2024-09-16 16:13 UTC, MaxGhenis commented
<img width="562" alt="image" src="https://github.com/user-attachments/assets/745892e7-90a2-493e-b169-c6f635df8ff4">

2024-09-17 09:24 UTC, PavelMakarchuk commented
> <img alt="image" width="562" src="https://private-user-images.githubusercontent.com/6076111/367836328-745892e7-90a2-493e-b169-c6f635df8ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjUwNTEsIm5iZiI6MTcyNjU2NDc1MSwicGF0aCI6Ii82MDc2MTExLzM2NzgzNjMyOC03NDU4OTJlNy05MGEyLTQ5M2UtYjE2OS1jNmY2MzVkZjhmZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMDkxOTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIxMzVjMDkyZTZmNDA2OTVmNDdiMzlmZTM4MDM4ZDIzYjJhOTY2ODRlYTYxZWZjMGU5NDg3ZGU2NDZkZWYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zqxMk6ZMn-wyJ5Qzv_h9-foz821zM_YIRJnpeJz29A0">

No idea how i missed that - added

2024-09-17 15:26 UTC, MaxGhenis approved these changes

2024-09-19 15:40 UTC, nikhilwoodruff commented on policyengine_us_data/datasets/acs/acs.py
> +    file_path = STORAGE_FOLDER / "acs_2022.h5"
Sorry could you just add a `url` attribute (see e.g. the ECPS, doesn't have to already exist)

2024-09-20 11:19 UTC, nikhilwoodruff commented on policyengine_us_data/datasets/acs/acs.py
> +    def __init__(self):
I don't think this syntax matches the other Raw [dataset] files.

2024-09-22 20:51 UTC, nikhilwoodruff commented
@MaxGhenis a few things (thanks @PavelMakarchuk; taking over the baton for this PR) you might want to take a look at (but not essential or blocking).

* I've moved from our implementation of QRFs in survey-enhance to a more lightweight wrapper over [quantile-forest](https://zillow.github.io/quantile-forest/index.html) which seems faster and better-written than mine. We still have the mean quantile ability. The new implementation wrapper is in `utils/qrf.py`.
* Seems like we shouldn't calibrate real estate taxes from the SOI? But I can add calibration targets for total rent and property taxes, any ideas on the definitive source to use? They match the ACS totals after imputation.

2024-09-22 21:27 UTC, MaxGhenis commented
Correct we should not calibrate real estate taxes from SOI. See #29 for other options.

2024-09-23 08:45 UTC, nikhilwoodruff commented
SNAP is looking really nice with the rent imputation: after applying [USDA's 82% take-up rate](https://www.fns.usda.gov/usamap), we get 103bn vs 107bn in 2023.

2024-09-23 09:43 UTC, nikhilwoodruff commented
Also tied in #67 here.

2024-09-23 10:28 UTC, nikhilwoodruff commented
Getting memory breaches but I'm going to merge since it ran locally.

2024-09-23 10:28 UTC, merged